name: update prod passwords

on:  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        ref: latest
    
    - name: set up r
      uses: r-lib/actions/setup-r@v2
    
    - name: install dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        working-directory: 'src/'
        extra-packages: |
          shinymanager

    - name: create password database
      run: Rscript src/create_credentials.R
      env: 
        PASSPHRASE: ${{secrets.SHINYMANAGER_PASSPHRASE}}
        GUEST_PW: ${{secrets.SHINYMANAGER_GUEST}}
        ADMIN_PW: ${{secrets.SHINYMANAGER_ADMIN}}
        USER_PW: ${{secrets.SHINYMANAGER_USER}}
    
    - name: create auth json
      id: create-auth-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "peek-a-moo.json"
        json: ${{ secrets.GCP_AUTH_JSON }}
        dir: "auth/"
        
    - name: deploy to heroku  
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "peek-a-moo"
        heroku_email: "allyson@datallurgy.com"
        buildpack: "vsv/heroku-buildpack-r"
        procfile: "web: R --file=dashboard/run.R --gui-none --no-save"
      env:
        HD_PASSPHRASE: ${{secrets.SHINYMANAGER_PASSPHRASE}}
